### ISSUE TITLE
Private repos issue

### ISSUE THREAD

**Issue by KrishT0** [webbedpiyush/easy-ghfetchWeb#1]
For private repos it should show a message or error toast, instead, it's downloading an empty zip with a success toast.

### Demo
- Private repo link pasted
![image](https://github.com/user-attachments/assets/97fc1ecc-b62c-48c1-83a9-b49681677833)

- Empty zip with success toast
![image](https://github.com/user-attachments/assets/81014871-0486-4e94-962b-6a1a92673d53)
![image](https://github.com/user-attachments/assets/60256545-ea6a-4c05-870d-6969115ddd5c)

**Comment by webbedpiyush** [comment]
thanks for pointing it out 
I will do this

**Comment by webbedpiyush** [comment]
![Screenshot from 2024-10-21 17-45-09](https://github.com/user-attachments/assets/4ea324b4-2008-4a1c-8b01-a39d89cc270a)
Done!
